name: Auto label Pull Requests
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
