name: Browser Tests

on:
  workflow_dispatch:
  push:

jobs:
  see_if_should_skip:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@a12175f6209d4805b5a163d723270be2a0dc7b36
        with:
          cancel_others: 'false'
          github_token: ${{ github.token }}
          paths: '["assets/**", "content/**", "data/**", "includes/**", "javascripts/**", "jest-puppeteer.config.js", "jest.config.js", "layouts/**", "lib/**", "middleware/**", "package-lock.json", "package.json", "server.js", "translations/**", "webpack.config.js"]'
  build:
    needs: see_if_should_skip
    runs-on: ubuntu-latest
    steps:
      # Each of these ifs needs to be repeated at each step to make sure the required check still runs
      # Even if if doesn't do anything
      - if: ${{ needs.see_if_should_skip.outputs.should_skip == 'false' }}
        name: Checkout
        uses: actions/checkout@v2

      - if: ${{ needs.see_if_should_skip.outputs.should_skip == 'false' }}
        name: Install
        uses: ianwalter/puppeteer@3.0.0
        with:
          args: npm ci

      - if: ${{ needs.see_if_should_skip.outputs.should_skip == 'false' }}
        name: Test
        uses: ianwalter/puppeteer@3.0.0
        with:
          args: npm run browser-test
