# The docs.github.com project has two repositories: github/docs (public) and github/docs-internal (private)
# 
# This GitHub Actions workflow keeps the main branch of those two repos in sync.
# 
# For more details, see https://github.com/repo-sync/repo-sync#how-it-works

name: Repo Sync

on:
  schedule:
  - cron: "*/15 * * * *" # every 15 minutes

env:
  FREEZE: ${{ secrets.FREEZE }}

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

    - name: Exit if repo is frozen
      if: ${{ env.FREEZE == 'true' }}
      run: |
        echo 'The repo is currently frozen! Exiting this workflow.'
        exit 1 # prevents further steps from running

    - name: Check out repo
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675

    - name: Sync repo to branch
      uses: repo-sync/github-sync@3832fe8e2be32372e1b3970bbae8e7079edeec88
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}
      with:
        source_repo: ${{ secrets.SOURCE_REPO }} # https://${access_token}@github.com/github/the-other-repo.git
        source_branch: main
        destination_branch: repo-sync
        github_token: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}

    - name: Create pull request
      uses: repo-sync/pull-request@ea6773388b83b337e4da9a223293309f2c3670e7
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}
      with:
        source_branch: repo-sync
        destination_branch: main
        pr_title: "repo sync"
        pr_body: "This is an automated pull request to sync changes between the public and private repos.\n\n:robot: This pull request should be merged (not squashed) to preserve continuity across repos, so please let a bot do the merging!"
        pr_label: automerge,autoupdate
        github_token: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}

    - name: Find pull request
      uses: juliangruber/find-pull-request-action@64d55773c959748ad30a4184f4dc102af1669f7b
      id: find-pull-request
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: repo-sync

    - name: Approve pull request
      if: ${{ steps.find-pull-request.outputs.number }}
      uses: juliangruber/approve-pull-request-action@c530832d4d346c597332e20e03605aa94fa150a8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}

    - name: Send Slack notification if workflow fails
      uses: rtCamp/action-slack-notify@e17352feaf9aee300bf0ebc1dfbf467d80438815
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.DOCS_ALERTS_SLACK_WEBHOOK }}
        SLACK_MESSAGE: The last repo-sync run for ${{github.repository}} failed. See https://github.com/${{github.repository}}/actions?query=workflow%3A%22Repo+Sync%22
