name: Repo Sync

on:
  schedule:
  - cron: "*/15 * * * *" # every 15 minutes

env:
  FREEZE: ${{ secrets.FREEZE }}

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

    - name: Exit if repo is frozen
      if: ${{ env.FREEZE == 'true' }}
      run: |
        echo 'The repo is currently frozen! Exiting this workflow.'
        exit 1 # prevents further steps from running

    - name: Check out repo
      uses: actions/checkout@v2

    - name: Sync repo to branch
      uses: repo-sync/github-sync@v2
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}
      with:
        source_repo: ${{ secrets.SOURCE_REPO }} # https://${access_token}@github.com/github/the-other-repo.git
        source_branch: main
        destination_branch: repo-sync
        github_token: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}

    - name: Create pull request
      uses: repo-sync/pull-request@v2
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}
      with:
        source_branch: repo-sync
        destination_branch: main
        pr_title: "repo sync"
        pr_body: "This is an automated pull request to sync changes between the public and private repos.\n\n:robot: This pull request should be merged (not squashed) to preserve continuity across repos, so please let a bot do the merging!"
        pr_label: automerge,autoupdate
        github_token: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}

    - name: Find pull request
      uses: juliangruber/find-pull-request-action@v1
      id: find-pull-request
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: repo-sync

    - name: Approve pull request
      if: ${{ steps.find-pull-request.outputs.number }}
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}

    - name: Send Slack notification if workflow fails
      uses: rtCamp/action-slack-notify@master
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.DOCS_ALERTS_SLACK_WEBHOOK }}
        SLACK_MESSAGE: The last repo-sync run for ${{github.repository}} failed. See https://github.com/${{github.repository}}/actions?query=workflow%3A%22Repo+Sync%22
