# NOTE: Changes to this file should also be applied to './test.yml' and './test-translations.yml'

name: Node.js Tests - Windows

on:
  schedule:
    - cron: "50 19 * * *" # once a day at 19:50 UTC / 11:50 PST

env:
  CI: true

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx standard

      - name: Check dependencies
        run: npm run check-deps

  test:
    if: github.repository == 'github/docs-internal'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        test-group: [content, meta, rendering, routing, unit, links-and-images]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      - name: Run tests
        run: npx jest tests/${{ matrix.test-group }}/
